In [1]:
import pandas as pd
import pylab as pl
import numpy as np

In [3]:
vols = pd.read_csv('C:/Users/usuario/Desktop/POSTGRAU_DATA_SCIENCE/PROJECTE_POSTGRAU/RECOMANADOR/dades_4_07_2016.csv')

In [4]:
vols

,Unnamed: 0,ID_Vuelo,Id_bitllet,dia_query,dia_query_dia_setmana,dias_antelacion,aerolinia,nombre_ciudad_origen,nombre_ciudad_destino,precio,fecha_salida,fecha_salida_dia_setmana,hora_salida,fecha_llegada,fecha_llegada_dia_setmana,hora_llegada,duracion,demanda,baixada_preu
0,73,BA2046,20,2015-11-17,dimarts,-35,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
1,152,BA2046,20,2015-11-18,dimecres,-34,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
2,404,BA2046,20,2015-11-22,diumenge,-30,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
3,754,BA2046,20,2015-11-27,divendres,-25,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
4,1104,BA2046,20,2015-12-02,dimecres,-20,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
5,1449,BA2046,20,2015-12-07,dilluns,-15,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
6,1784,BA2046,20,2015-12-12,dissabte,-10,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
7,480,BA2046,21,2015-11-23,dilluns,-30,British Airways p.l.c.,Barcelona,London,77.69,2015-12-23,dimecres,07:00,2015-12-23,dimecres,08:10,130,0,1
8,830,BA2046,21,2015-11-28,dissabte,-25,British Airways p.l.c.,Barcelona,London,77.69,2015-12-23,dimecres,07:00,2015-12-23,dimecres,08:10,130,0,1
9,1174,BA2046,21,2015-12-03,dijous,-20,British Airways p.l.c.,Barcelona,London,77.69,2015-12-23,dimecres,07:00,2015-12-23,dimecres,08:10,130,0,1
10,1524,BA2046,21,2015-12-08,dimarts,-15,British Airways p.l.c.,Barcelona,London,77.69,2015-12-23,dimecres,07:00,2015-12-23,dimecres,08:10,130,0,1
11,1855,BA2046,21,2015-12-13,diumenge,-10,British Airways p.l.c.,Barcelona,London,77.69,2015-12-23,dimecres,07:00,2015-12-23,dimecres,08:10,130,0,1
12,213,BA2046,22,2015-11-19,dijous,-35,British Airways p.l.c.,Barcelona,London,77.69,2015-12-24,dijous,07:00,2015-12-24,dijous,08:10,130,0,1
13,551,BA2046,22,2015-11-24,dimarts,-30,British Airways p.l.c.,Barcelona,London,77.69,2015-12-24,dijous,07:00,2015-12-24,dijous,08:10,130,0,1
14,900,BA2046,22,2015-11-29,diumenge,-25,British Airways p.l.c.,Barcelona,London,77.69,2015-12-24,dijous,07:00,2015-12-24,dijous,08:10,130,0,1
15,1245,BA2046,22,2015-12-04,divendres,-20,British Airways p.l.c.,Barcelona,London,77.69,2015-12-24,dijous,07:00,2015-12-24,dijous,08:10,130,0,1
16,1595,BA2046,22,2015-12-09,dimecres,-15,British Airways p.l.c.,Barcelona,London,77.69,2015-12-24,dijous,07:00,2015-12-24,dijous,08:10,130,0,1
17,1925,BA2046,22,2015-12-14,dilluns,-10,British Airways p.l.c.,Barcelona,London,77.69,2015-12-24,dijous,07:00,2015-12-24,dijous,08:10,130,0,1
18,273,BA2046,23,2015-11-20,divendres,-35,British Airways p.l.c.,Barcelona,London,97.69,2015-12-25,divendres,13:00,2015-12-25,divendres,14:10,130,0,0
19,619,BA2046,23,2015-11-25,dimecres,-30,British Airways p.l.c.,Barcelona,London,77.69,2015-12-25,divendres,13:00,2015-12-25,divendres,14:10,130,0,1
20,969,BA2046,23,2015-11-30,dilluns,-25,British Airways p.l.c.,Barcelona,London,77.69,2015-12-25,divendres,13:00,2015-12-25,divendres,14:10,130,0,1
21,1314,BA2046,23,2015-12-05,dissabte,-20,British Airways p.l.c.,Barcelona,London,77.69,2015-12-25,divendres,13:00,2015-12-25,divendres,14:10,130,0,1
22,1659,BA2046,23,2015-12-10,dijous,-15,British Airways p.l.c.,Barcelona,London,77.69,2015-12-25,divendres,13:00,2015-12-25,divendres,14:10,130,0,1
23,1986,BA2046,23,2015-12-15,dimarts,-10,British Airways p.l.c.,Barcelona,London,77.69,2015-12-25,divendres,13:00,2015-12-25,divendres,14:10,130,0,1
24,25,BA2047,24,2015-11-16,dilluns,-35,British Airways p.l.c.,Barcelona,London,77.69,2015-12-21,dilluns,17:45,2015-12-21,dilluns,19:00,135,0,1
25,343,BA2047,24,2015-11-21,dissabte,-30,British Airways p.l.c.,Barcelona,London,77.69,2015-12-21,dilluns,17:45,2015-12-21,dilluns,19:00,135,0,1
26,693,BA2047,24,2015-11-26,dijous,-25,British Airways p.l.c.,Barcelona,London,77.69,2015-12-21,dilluns,17:45,2015-12-21,dilluns,19:00,135,0,1
27,1043,BA2047,24,2015-12-01,dimarts,-20,British Airways p.l.c.,Barcelona,London,77.69,2015-12-21,dilluns,17:45,2015-12-21,dilluns,19:00,135,0,1
28,1388,BA2047,24,2015-12-06,diumenge,-15,British Airways p.l.c.,Barcelona,London,77.69,2015-12-21,dilluns,17:45,2015-12-21,dilluns,19:00,135,0,1
29,1728,BA2047,24,2015-12-11,divendres,-10,British Airways p.l.c.,Barcelona,London,77.69,2015-12-21,dilluns,17:45,2015-12-21,dilluns,19:00,135,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73726,43291,VY8994,2414,2016-04-15,divendres,-133,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73727,43776,VY8994,2414,2016-04-16,dissabte,-132,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73728,44260,VY8994,2414,2016-04-17,diumenge,-131,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73729,44744,VY8994,2414,2016-04-18,dilluns,-130,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73730,45228,VY8994,2414,2016-04-19,dimarts,-129,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73731,45713,VY8994,2414,2016-04-20,dimecres,-128,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73732,46198,VY8994,2414,2016-04-21,dijous,-127,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73733,46683,VY8994,2414,2016-04-22,divendres,-126,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73734,47168,VY8994,2414,2016-04-23,dissabte,-125,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73735,47653,VY8994,2414,2016-04-24,diumenge,-124,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73736,48138,VY8994,2414,2016-04-25,dilluns,-123,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73737,48623,VY8994,2414,2016-04-26,dimarts,-122,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73738,49108,VY8994,2414,2016-04-27,dimecres,-121,Vueling Airlines S.A.,Barcelona,Brussels,115.33,2016-08-26,divendres,15:30,2016-08-26,divendres,17:40,130,1,1
73739,41380,VY8994,2415,2016-04-11,dilluns,-140,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73740,41865,VY8994,2415,2016-04-12,dimarts,-139,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73741,42350,VY8994,2415,2016-04-13,dimecres,-138,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73742,42835,VY8994,2415,2016-04-14,dijous,-137,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73743,43320,VY8994,2415,2016-04-15,divendres,-136,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73744,43805,VY8994,2415,2016-04-16,dissabte,-135,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73745,44289,VY8994,2415,2016-04-17,diumenge,-134,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73746,44773,VY8994,2415,2016-04-18,dilluns,-133,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73747,45257,VY8994,2415,2016-04-19,dimarts,-132,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73748,45742,VY8994,2415,2016-04-20,dimecres,-131,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73749,46227,VY8994,2415,2016-04-21,dijous,-130,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73750,46712,VY8994,2415,2016-04-22,divendres,-129,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73751,47197,VY8994,2415,2016-04-23,dissabte,-128,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73752,47682,VY8994,2415,2016-04-24,diumenge,-127,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73753,48167,VY8994,2415,2016-04-25,dilluns,-126,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73754,48652,VY8994,2415,2016-04-26,dimarts,-125,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1
73755,49137,VY8994,2415,2016-04-27,dimecres,-124,Vueling Airlines S.A.,Barcelona,Brussels,92.33,2016-08-29,dilluns,15:30,2016-08-29,dilluns,17:40,130,0,1

In [5]:
list(vols.columns.values)

['Unnamed: 0',
 'ID_Vuelo',
 'Id_bitllet',
 'dia_query',
 'dia_query_dia_setmana',
 'dias_antelacion',
 'aerolinia',
 'nombre_ciudad_origen',
 'nombre_ciudad_destino',
 'precio',
 'fecha_salida',
 'fecha_salida_dia_setmana',
 'hora_salida',
 'fecha_llegada',
 'fecha_llegada_dia_setmana',
 'hora_llegada',
 'duracion',
 'demanda',
 'baixada_preu']

In [6]:
print vols.head()

SyntaxError: invalid syntax (<ipython-input-6-116709645afd>, line 1)

In [7]:
print vols.describe()

SyntaxError: invalid syntax (<ipython-input-7-62524ff77005>, line 1)

In [8]:
from sklearn import preprocessing
['Unnamed: 0',
 'ID_Vuelo',
 'Id_bitllet',
 'dia_query',
 'dia_query_dia_setmana',
 'dias_antelacion',
 'aerolinia',
 'nombre_ciudad_origen',
 'nombre_ciudad_destino',
 'precio',
 'fecha_salida',
 'fecha_salida_dia_setmana',
 'hora_salida',
 'fecha_llegada',
 'fecha_llegada_dia_setmana',
 'hora_llegada',
 'duracion',
 'demanda',
 'baixada_preu']

X = vols[["aerolinia","dia_query","precio","dias_antelacion", "nombre_ciudad_destino",
          "nombre_ciudad_destino", "fecha_salida_dia_setmana", "demanda"]]
Y = vols[["baixada_preu"]]
X = pd.get_dummies(vols[["precio","dias_antelacion", "nombre_ciudad_destino", "fecha_salida_dia_setmana", "demanda"]])
X

,precio,dias_antelacion,demanda,nombre_ciudad_destino_Birmingham,nombre_ciudad_destino_Brussels,nombre_ciudad_destino_Copenhagen,nombre_ciudad_destino_Dublin,nombre_ciudad_destino_London,nombre_ciudad_destino_Madrid,nombre_ciudad_destino_Moscow,nombre_ciudad_destino_Munich,nombre_ciudad_destino_Palma Mallorca,nombre_ciudad_destino_Paris,fecha_salida_dia_setmana_dijous,fecha_salida_dia_setmana_dilluns,fecha_salida_dia_setmana_dimarts,fecha_salida_dia_setmana_dimecres,fecha_salida_dia_setmana_dissabte,fecha_salida_dia_setmana_diumenge,fecha_salida_dia_setmana_divendres
0,77.69,-35,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
1,77.69,-34,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
2,77.69,-30,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
3,77.69,-25,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
4,77.69,-20,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
5,77.69,-15,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
6,77.69,-10,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
7,77.69,-30,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
8,77.69,-25,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
9,77.69,-20,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
10,77.69,-15,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
11,77.69,-10,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
12,77.69,-35,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
13,77.69,-30,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
14,77.69,-25,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
15,77.69,-20,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
16,77.69,-15,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
17,77.69,-10,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
18,97.69,-35,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
19,77.69,-30,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
20,77.69,-25,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
21,77.69,-20,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
22,77.69,-15,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
23,77.69,-10,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
24,77.69,-35,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0
25,77.69,-30,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0
26,77.69,-25,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0
27,77.69,-20,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0
28,77.69,-15,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0
29,77.69,-10,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73726,115.33,-133,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73727,115.33,-132,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73728,115.33,-131,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73729,115.33,-130,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73730,115.33,-129,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73731,115.33,-128,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73732,115.33,-127,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73733,115.33,-126,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73734,115.33,-125,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73735,115.33,-124,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73736,115.33,-123,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73737,115.33,-122,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73738,115.33,-121,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
73739,92.33,-140,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73740,92.33,-139,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73741,92.33,-138,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73742,92.33,-137,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73743,92.33,-136,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73744,92.33,-135,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73745,92.33,-134,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73746,92.33,-133,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73747,92.33,-132,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73748,92.33,-131,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73749,92.33,-130,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73750,92.33,-129,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73751,92.33,-128,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73752,92.33,-127,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73753,92.33,-126,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73754,92.33,-125,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73755,92.33,-124,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [9]:
from sklearn.metrics import accuracy_score

In [10]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 150)
forest = forest.fit(X, Y)
predictions = forest.predict(X)
accuracy_score(Y, predictions)

E:\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()

0.92256901133467106

In [10]:
vols["dias_antelacion", "nombre_ciudad_destino", "fecha_salida_dia_setmana", "demanda"]

KeyError: ('dias_antelacion', 'nombre_ciudad_destino', 'fecha_salida_dia_setmana', 'demanda')