In [1]:
import pandas as pd
import pylab as pl
import numpy as np

In [2]:
vols = pd.read_csv('/home/roger/Escritorio/RECOMANADOR/dades_4_07_2016.csv')

In [45]:
vols.head(n=10)

,Unnamed: 0,ID_Vuelo,Id_bitllet,dia_query,dia_query_dia_setmana,dias_antelacion,aerolinia,nombre_ciudad_origen,nombre_ciudad_destino,precio,fecha_salida,fecha_salida_dia_setmana,hora_salida,fecha_llegada,fecha_llegada_dia_setmana,hora_llegada,duracion,demanda,baixada_preu
0,73,BA2046,20,2015-11-17,dimarts,-35,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
1,152,BA2046,20,2015-11-18,dimecres,-34,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
2,404,BA2046,20,2015-11-22,diumenge,-30,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
3,754,BA2046,20,2015-11-27,divendres,-25,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
4,1104,BA2046,20,2015-12-02,dimecres,-20,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
5,1449,BA2046,20,2015-12-07,dilluns,-15,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
6,1784,BA2046,20,2015-12-12,dissabte,-10,British Airways p.l.c.,Barcelona,London,77.69,2015-12-22,dimarts,07:00,2015-12-22,dimarts,08:10,130,0,1
7,480,BA2046,21,2015-11-23,dilluns,-30,British Airways p.l.c.,Barcelona,London,77.69,2015-12-23,dimecres,07:00,2015-12-23,dimecres,08:10,130,0,1
8,830,BA2046,21,2015-11-28,dissabte,-25,British Airways p.l.c.,Barcelona,London,77.69,2015-12-23,dimecres,07:00,2015-12-23,dimecres,08:10,130,0,1
9,1174,BA2046,21,2015-12-03,dijous,-20,British Airways p.l.c.,Barcelona,London,77.69,2015-12-23,dimecres,07:00,2015-12-23,dimecres,08:10,130,0,1

In [4]:
list(vols.columns.values)

['Unnamed: 0',
 'ID_Vuelo',
 'Id_bitllet',
 'dia_query',
 'dia_query_dia_setmana',
 'dias_antelacion',
 'aerolinia',
 'nombre_ciudad_origen',
 'nombre_ciudad_destino',
 'precio',
 'fecha_salida',
 'fecha_salida_dia_setmana',
 'hora_salida',
 'fecha_llegada',
 'fecha_llegada_dia_setmana',
 'hora_llegada',
 'duracion',
 'demanda',
 'baixada_preu']

In [5]:
print vols.head()

   Unnamed: 0 ID_Vuelo  Id_bitllet   dia_query dia_query_dia_setmana  \
0          73   BA2046          20  2015-11-17               dimarts
1         152   BA2046          20  2015-11-18              dimecres
2         404   BA2046          20  2015-11-22              diumenge
3         754   BA2046          20  2015-11-27             divendres
4        1104   BA2046          20  2015-12-02              dimecres

   dias_antelacion               aerolinia nombre_ciudad_origen  \
0              -35  British Airways p.l.c.            Barcelona
1              -34  British Airways p.l.c.            Barcelona
2              -30  British Airways p.l.c.            Barcelona
3              -25  British Airways p.l.c.            Barcelona
4              -20  British Airways p.l.c.            Barcelona

  nombre_ciudad_destino  precio fecha_salida fecha_salida_dia_setmana  \
0                London   77.69   2015-12-22                  dimarts
1                London   77.69   2015-12-22                  dimarts
2                London   77.69   2015-12-22                  dimarts
3                London   77.69   2015-12-22                  dimarts
4                London   77.69   2015-12-22                  dimarts

  hora_salida fecha_llegada fecha_llegada_dia_setmana hora_llegada  duracion  \
0       07:00    2015-12-22                   dimarts        08:10       130
1       07:00    2015-12-22                   dimarts        08:10       130
2       07:00    2015-12-22                   dimarts        08:10       130
3       07:00    2015-12-22                   dimarts        08:10       130
4       07:00    2015-12-22                   dimarts        08:10       130

   demanda  baixada_preu
0        0             1
1        0             1
2        0             1
3        0             1
4        0             1

In [6]:
print vols.describe()

         Unnamed: 0    Id_bitllet  dias_antelacion        precio  \
count  73756.000000  73756.000000     73756.000000  73756.000000
mean   37289.521476   1254.455854       -47.913580    106.976617
std    21315.366381    681.070240        35.124241     62.095209
min        1.000000     20.000000      -142.000000     29.580000
25%    18844.750000    684.000000       -61.000000     60.330000
50%    37288.500000   1245.000000       -38.000000     95.330000
75%    55746.250000   1866.000000       -24.000000    143.330000
max    74201.000000   2415.000000         0.000000    491.750000

           duracion       demanda  baixada_preu
count  73756.000000  73756.000000  73756.000000
mean     117.269917      0.244929      0.662929
std       50.460589      0.430048      0.472713
min       45.000000      0.000000      0.000000
25%       80.000000      0.000000      0.000000
50%      125.000000      0.000000      1.000000
75%      130.000000      0.000000      1.000000
max      265.000000      1.000000      1.000000

In [46]:
from sklearn import preprocessing
#X = vols[["fecha_llegada_dia_setmana","aerolinia","dia_query","precio","dias_antelacion", "nombre_ciudad_destino",
#          "nombre_ciudad_destino", "fecha_salida_dia_setmana", "demanda","dia_query_dia_setmana","dias_antelacion","aerolinia"]]
#X_lin = vols[["fecha_salida_dia_setmana", "dia_query_dia_setmana", "dias_antelacion", "nombre_ciudad_destino",
#              "aerolinia", "duracion", "demanda"]]
#X = pd.get_dummies(vols[["precio","dias_antelacion", "nombre_ciudad_destino", "fecha_salida_dia_setmana", "demanda"]])
Y = vols[["baixada_preu"]]
X = pd.get_dummies(vols[["precio","fecha_salida_dia_setmana", "dia_query_dia_setmana", "dias_antelacion", "nombre_ciudad_destino",
              "aerolinia", "duracion", "demanda"]])
X.head(n=10)

,precio,dias_antelacion,duracion,demanda,fecha_salida_dia_setmana_dijous,fecha_salida_dia_setmana_dilluns,fecha_salida_dia_setmana_dimarts,fecha_salida_dia_setmana_dimecres,fecha_salida_dia_setmana_dissabte,fecha_salida_dia_setmana_diumenge,...,nombre_ciudad_destino_London,nombre_ciudad_destino_Madrid,nombre_ciudad_destino_Moscow,nombre_ciudad_destino_Munich,nombre_ciudad_destino_Palma Mallorca,nombre_ciudad_destino_Paris,aerolinia_British Airways p.l.c.,aerolinia_Deutsche Lufthansa AG,aerolinia_Iberia Lineas Aereas de Espana S.A.,aerolinia_Vueling Airlines S.A.
0,77.69,-35,130,0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,77.69,-34,130,0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,77.69,-30,130,0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,77.69,-25,130,0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,77.69,-20,130,0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,77.69,-15,130,0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
6,77.69,-10,130,0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,77.69,-30,130,0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,77.69,-25,130,0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9,77.69,-20,130,0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [41]:
from sklearn.linear_model import LinearRegression
import math
Y = vols[["precio"]]
X = pd.get_dummies(vols[["fecha_salida_dia_setmana", "dia_query_dia_setmana", "dias_antelacion", 
                         "nombre_ciudad_destino", "aerolinia", "duracion", "demanda"]])
X
est = LinearRegression(fit_intercept=True) # Call the constructor of the estimator 
est
from sklearn import linear_model
clf = linear_model.LinearRegression() 
clf.fit (X, Y)  # Perform the fitting
clf.coef_

array([[  6.46481118e-02,  -1.35453753e+00,   1.90650537e+01,
         -7.80598361e+00,   1.35681176e+01,  -1.03441195e+01,
         -1.28930729e+01,  -2.96748459e+00,   2.31903023e+01,
         -2.74775940e+00,   8.70086749e-02,   5.14011955e-01,
         -7.38025287e-01,  -1.21161902e-01,  -1.79584612e-01,
          2.92995324e-01,   1.44755848e-01,   1.57542233e+01,
         -3.91576956e+01,   7.34534736e+01,   5.67310632e+01,
         -1.79280561e+01,  -7.33084806e+01,   2.30438946e+02,
         -2.13993603e+01,  -1.72236363e+02,  -5.23477503e+01,
         -1.23112245e+01,   4.79421983e+01,  -1.70669462e+01,
         -1.85640276e+01]])

In [42]:
clf.score(X, Y)

0.50065101273137769

In [20]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
Y = vols[["baixada_preu"]]
X = pd.get_dummies(vols[["precio","fecha_salida_dia_setmana", "dia_query_dia_setmana", "dias_antelacion", "nombre_ciudad_destino",
              "aerolinia", "duracion", "demanda"]])
X
forest = RandomForestClassifier(n_estimators = 150)
forest = forest.fit(X, Y)
predictions = forest.predict(X)
accuracy_score(Y, predictions)

/home/roger/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()

0.9511361787515592